spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: debug
core:
  security:
    enable-ip-filter: false   # 기본값은 false (local/dev)
    allowed-ips:
      - 127.0.0.1
    api-key: dnLDp4Et6qXGXawyj4JRjOUjSyDjtl8/XxsAp2Fb8AAqTJ86M0LFDNQ69yBlxr9stZF7jIqjC2VMGALENV98RA== #mock
