spring:
  application:
    name: teenyfinny_core
  lifecycle:
    timeout-per-shutdown-phase: 60S # ??: ?, ???? ?? ????
  profiles:
    include: secret
  jackson:
    time-zone: Asia/Seoul
  mvc:
    servlet:
      path: /core

server:
  port: 8080
  shutdown: graceful
  timezone: Asia/Seoul

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, metrics, info, drain, prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name:teenyfinny-core}
